### ISSUE TITLE
CloudHub License

### ISSUE THREAD

**Issue by cgorshing** [mulesoft/mulesoft-docs#1014]
I asked this question on Slack, but I thought it might be good to have documented someplace so I could point people to the official documentation. I couldn't find it anywhere else.

For licensing of apps running on CH. The sum of vCores is what matters correct? Only running vcore? So if a customer has a license of 2vCores, then they could run 10 apps as .2vCores (or 20 apps at .1vCore). Correct? Is it only apps that are running that counts towards usage, or do undeployed/stopped apps count as well?

And with workers, if an app has 4 workers at .2 vCores, then this would count as .8 vCores towards the license, again only if the app is running.

I'm finding some items around https://docs.mulesoft.com/runtime-manager/managing-cloudhub-specific-settings but doesn't answer all my questions

**Comment by fermujica** [comment]
Hi Chad, 
You are correct. vCores processing is consumed by running applications. 
Undeployed/stopped apps do not consume vCore availability. 

Also true that this is not specifically stated in the docs. 
I'll add a couple of notes around the Runtime Manager Docs.
