### ISSUE TITLE
MUnit Migration Guide Link

### ISSUE THREAD

**Issue by cgorshing** [mulesoft/mulesoft-docs#1025]
At the bottom of https://docs.mulesoft.com/munit/v/1.3.0/ there is a link for _MUnit 1.2.1 Migration Guide_ that does not exist. There is a munit-1.3.0-migration-guide.adoc file but that is all I see.

Is the link suppose to be the file above, or is there a 1.2.1 migration guide to be written?

**Comment by fermujica** [comment]
Thanks Chad!
I forgot to trakch the change using this issue.
This was fixed: https://docs.mulesoft.com/munit/v/1.3.0/munit-1.3.0-migration-guide
