### ISSUE TITLE
Unable to locate maven archetype for new Connector Project

### ISSUE THREAD

**Issue by joshrosso** [mulesoft/mulesoft-docs#1137]
[In older docs](https://docs.mulesoft.com/anypoint-connector-devkit/v/3.3/using-the-cloud-connector-archetype#example), the Maven archetype was available for developers looking to bootstrap a Connector project. I was unable to locate any such doc for 3.8.

Assuming this does not exist in docs, my recommended solution is:

1. Create a doc-reference page containing all relevant archetypes (e.g. mule projects, connectors, etc)

2. From [Setting Up Your Development Env](https://docs.mulesoft.com/anypoint-connector-devkit/v/3.8/setting-up-your-dev-environment)], add a link to the aforementioned connector archetype reference.

If MS approves this approach I will create a PR.

**Comment by sharkberto** [comment]
Great idea, Josh. We were discussing this topic of archetypes, specifically regarding archetypes for Mule projects accessible through Maven commands. We can at the least work on cleaning up the archetype reference for Mule 3.8. I see a devkit cloud connector archetype for Devkit 3.9 - will try to generate a Connector proj using it, and can discuss how to provide better access to the Maven tools for generating projects -- we would certainly appreciate your help on that.

**Comment by sharkberto** [comment]
https://docs.mulesoft.com/mule-user-guide/v/3.8/using-maven-with-mule There are docs about using archetypes to create examples, modules and projects in https://docs.mulesoft.com/mule-user-guide/v/3.8/extending that could be generalized and put into one doc, placed in "Using Maven with Mule", linked to from Setting up your dev env

**Comment by george-hoffer** [comment]
Hi Josh, Exchange now provides the Dependency Snippets feature for each connector for dependency info. See https://www.anypoint.mulesoft.com/exchange/?type=connector. I added notes about this feature to these docs: 
• Configuring Maven to Work with Mule - https://docs.mulesoft.com/mule-user-guide/v/3.8/configuring-maven-to-work-with-mule-esb (in versions 3.5 - 3.8)
• Using Maven with Mule - https://docs.mulesoft.com/mule-user-guide/v/3.8/using-maven-with-mule

If this is sufficient for your request, would you close this issue?  (Thank you)
