### ISSUE TITLE
Add a mod_rewrite or something for "current" version path

### ISSUE THREAD

**Issue by StoicNZ** [mulesoft/mulesoft-docs#1290]

**Comment by StoicNZ** [comment]
Bah, hit enter by mistake. So if you look at Atlassian's documentation for instance, they have an alias set up for "current" in the URL path. It's a pain in the ass Googling for Mule docs and it always links to 3.6 or 3.7 because that's got the most Google search cred.

Add current path to your web server and redirect to latest version or just clone the current version to /current/ path. 

ie https://docs.mulesoft.com/mule-user-guide/v/3.8/tuning-performance

This should link to the same article/version:
https://docs.mulesoft.com/mule-user-guide/v/current/tuning-performance

Bam, solved your search engine results issue. Not sure how you'd throw it in the Git repo, likely just have a placeholder and throw it into your build/deploy process.

**Comment by sharkberto** [comment]
Hi @StoicNZ - thanks for your input. We plan to change the process soon so the latest version has a static URL.
