### ISSUE TITLE
Fix all links to java.net

### ISSUE THREAD

**Issue by mojavelinux** [mulesoft/mulesoft-docs#1405]
This week, java.net was taken off line without any redirects. Therefore, all links to java.net in the MuleSoft documentation are now broken.

Here's a report of unique broken links by content document:

* anypoint-connector-devkit/v/3.4/connector-to-restful-service-with-jersey-client-example.adoc
  - `https://jersey.java.net/documentation/1.6/user-guide.html`
  - `https://jersey.java.net/documentation/1.6/user-guide.html#client-api`
  - `https://jersey.java.net/nonav/apidocs/1.12/jersey/contribs/jersey-oauth/oauth-client/com/sun/jersey/oauth/client/OAuthClientFilter.html`
* anypoint-connector-devkit/v/3.5/creating-a-connector-for-a-restful-api-using-jersey.adoc
  - `https://jersey.java.net/documentation/1.6/user-guide.html`
  - `https://jersey.java.net/documentation/1.6/user-guide.html#client-api`
  - `https://jersey.java.net/nonav/apidocs/1.12/jersey/contribs/jersey-oauth/oauth-client/com/sun/jersey/oauth/client/OAuthClientFilter.html`
* anypoint-connector-devkit/v/3.8/devkit-tutorial.adoc
  - `https://jersey.java.net/documentation/latest/client.html`
* mule-user-guide/v/3.2/jersey-module-reference.adoc
  - `https://jersey.dev.java.net/`
  - `http://jersey.java.net/documentation/1.6/user-guide.html`
* mule-user-guide/v/3.2/rss-module-reference.adoc
  - `https://rome.dev.java.net/`
* mule-user-guide/v/3.3/jersey-module-reference.adoc
  - `https://jersey.dev.java.net/`
  - `http://jersey.java.net/documentation/1.6/user-guide.html`
  - `http://java.net/projects/rome/pages/Home`
* mule-user-guide/v/3.3/rss-module-reference.adoc
  - `https://rome.dev.java.net/`
* mule-user-guide/v/3.4/jersey-module-reference.adoc
  - `https://jersey.dev.java.net/`
  - `http://jersey.dev.java.net/`
  - `http://jersey.java.net/documentation/1.6/user-guide.html`
  - `http://jersey.dev.java.net/`
* mule-user-guide/v/3.4/rss-module-reference.adoc
  - `http://java.net/projects/rome/pages/Home`
* mule-user-guide/v/3.5/jersey-module-reference.adoc
  - **NOTE:** for some reason, all the links are missing from this file
* mule-user-guide/v/3.5/rss-module-reference.adoc
  - `http://java.net/projects/rome/pages/Home`
* mule-user-guide/v/3.6/jersey-module-reference.adoc
  - `https://jersey.java.net/documentation/latest/index.html`
  - `https://jax-rs-spec.java.net/`
  - `https://jersey.java.net/`
  - `https://jersey.java.net/nonav/apidocs/1.12/jersey/javax/ws/rs/ext/ContextResolver.html`
  - `http://jersey.java.net/documentation/1.6/user-guide.html`
  - `http://jersey.dev.java.net/`
* mule-user-guide/v/3.6/rss-module-reference.adoc
  - `http://java.net/projects/rome/pages/Home`
* mule-user-guide/v/3.7/jersey-module-reference.adoc
  - `https://jersey.java.net/documentation/latest/index.html`
  - `https://jax-rs-spec.java.net/`
  - `https://jersey.java.net/`
  - `https://jersey.java.net/nonav/apidocs/1.12/jersey/javax/ws/rs/ext/ContextResolver.html`
  - `http://jersey.java.net/documentation/1.6/user-guide.html`
* mule-user-guide/v/3.7/rss-module-reference.adoc
  - `http://java.net/projects/rome/pages/Home`
* mule-user-guide/v/3.8/jersey-module-reference.adoc
  - `https://jersey.java.net/documentation/latest/index.html`
  - `https://jax-rs-spec.java.net/`
  - `https://jersey.java.net/`
  - `https://jersey.java.net/nonav/apidocs/1.12/jersey/javax/ws/rs/ext/ContextResolver.html`
  - `http://jersey.java.net/documentation/1.6/user-guide.html`
  - `http://jersey.dev.java.net/`
* mule-user-guide/v/3.8/rss-module-reference.adoc
  - `http://java.net/projects/rome/pages/Home`

**Comment by sleslie23** [comment]
Thanks @mojavelinux ! I'll try to get the team to fix these. If not, I'll fix these when I get back from vacation (July 5).

**Comment by mojavelinux** [comment]
The jersey.java.net URLs are at least redirecting to the home page of the new Jersey site. However, the Rome links are still broken.

**Comment by george-hoffer** [comment]
Removed the RSS Module Reference java.net references in 3.2 - 3.9.

**Comment by george-hoffer** [comment]
Fixed links as requested.
