### ISSUE TITLE
sub-header div position fixed moves page content

### ISSUE THREAD

**Issue by ty10r** [mulesoft/mulesoft-docs#15]
When scrolling down past the sub-header div, the sub-header becomes fixed at the top of the page.

When the div becomes fixed, the space it had been occupying above the content is no longer reserved for it, making the content all skip upwards.

This motion of the entire page content makes every doc page less readable.

Checkout [Bootstrap Affix](http://www.w3schools.com/bootstrap/bootstrap_affix.asp) for possible solution.

**Comment by ty10r** [comment]
Is this the right repo to submit this issue to?

**Comment by george-hoffer** [comment]
Created as DOCS-1505, and this issue closed.
