### ISSUE TITLE
SharePoint online connector doesn't show up from exchange

### ISSUE THREAD

**Issue by ahkim** [mulesoft/mulesoft-docs#1592]
https://docs.mulesoft.com/mule-user-guide/v/3.8/microsoft-sharepoint-online-connector#to-install-the-connector

SharePoint online connector doesn't show up. Please indicate a repository address if I have to add to see it available.

**Comment by george-hoffer** [comment]
Hi - Please check this URL to locate the SharePoint connector: https://anypoint.mulesoft.com/exchange/?search=sharepoint
You can also check Exchange 1 at https://anypoint.mulesoft.com/exchange1
For more info, see https://docs.mulesoft.com/mule-user-guide/v/3.8/installing-connectors

**Comment by george-hoffer** [comment]
Ahkim - The SharePoint Online Connector was released on Sept 11, 2017. The doc appeared early and was pulled back. Sorry about the confusion.
