### ISSUE TITLE
Studio 7 beta release download link not present

### ISSUE THREAD

**Issue by sudarshan89** [mulesoft/mulesoft-docs#1641]
In the studio documentation page there not link to actually download Studio 7?

Referring to this [help page](https://beta-anypt.docs-stgx.mulesoft.com/anypoint-studio/v/7/to-download-and-install-studio-beta)

**Comment by fermujica** [comment]
Hi! 
We are evaluating adding a download link from the docs. 
In the meantime, you can download the studio beta from official the download site: https://www.mulesoft.com/platform/mule-studio-beta
