### ISSUE TITLE
Anytime Runtime Manager

### ISSUE THREAD

**Issue by Kapaski** [mulesoft/mulesoft-docs#197]
Hi there, 

In the doc of 

https://github.com/mulesoft/mulesoft-docs/blob/master/anypoint-platform-on-premises/v/1.0/installing-anypoint-runtime-manager-on-premises-edition.adoc

this is metioned in the secion of `Installing ARM`

        Download the Anypoint Docker Setup package

but there is no link or reference that points me to the download, could anyone help?

Regards
James

**Comment by nearnshaw** [comment]
Hi Kapaski, to install the Anypoint Platform on Premises, please refer to this other doc instead:

https://docs.mulesoft.com/anypoint-platform-on-premises/v/1.0/installing-anypoint-on-premises

The entire process has now been reviewed to make use of the tool Rancher, which simplifies things plenty.

Hope you find this other content more helpful, and please let us know if you find anything else wrong with the documentation! :)
Cheers,
Nico
