### ISSUE TITLE
Missing PGP Signature option documentation

### ISSUE THREAD

**Issue by adrianpineyro** [mulesoft/mulesoft-docs#2223]
At https://docs.mulesoft.com/mule-user-guide/v/3.9/mule-digital-signature-processor

we are missing documentation about PGP Signer:

![screen shot 2018-02-14 at 17 13 45](https://user-images.githubusercontent.com/1303865/36225754-7812401c-11aa-11e8-8764-594d39ab1db3.png)

![screen shot 2018-02-14 at 17 13 53](https://user-images.githubusercontent.com/1303865/36225755-78350a0c-11aa-11e8-92b0-a085ed0ca171.png)

This is part of AES 1.7.x, compatible with 3.9.x

**Comment by adrianmartinmulesoft** [comment]
There's a DOCS Jira created https://www.mulesoft.org/jira/browse/DOCS-1876. We have support cases about this.

**Comment by tapasviparmar** [comment]
Is this resolved? We are facing issue with it. Not getting any help especially for PGP Sign(response)
