### ISSUE TITLE
Bad image reference: mule-user-guide/v/4.0/intro-studio.adoc

### ISSUE THREAD

**Issue by rogerkohler** [mulesoft/mulesoft-docs#2328]
Line 18 of this file references the Studio pallet in a document section describing User Credential toolbar.  Either the pallet reference should be replaced with an appropriate image (perhaps studio-credentials.png?) or removed entirely.

**Comment by fermujica** [comment]
Indeed there was a broken image. I just updated the content. 

Thanks for reporting!
