### ISSUE TITLE
Spelling error in MUnit Maven Plugin settings

### ISSUE THREAD

**Issue by solarch** [mulesoft/mulesoft-docs#256]
Under MUnit Maven Plugin the following xml code should have a dot instead of a hyphen:

`<version>${munit-version}</version>`

In order to match the version placeholder below under MUnit Dependencies, should be:

`<version>${munit.version}</version>`

**Comment by george-hoffer** [comment]
Fixed as requested. Closing this issue. If you have further concerns, please open a new issue. Thank you for helping improve MuleSoft documentation.
