### ISSUE TITLE
Setting Up External Identity doesn't clearly differentiate between client management and  user management

### ISSUE THREAD

**Issue by adrianpineyro** [mulesoft/mulesoft-docs#260]
The explanations, as requested by a customer, is:

If you want to configure client management (OAuth 2.0) for your Anypoint Organization, which means that you will be able to apply OAuth 2.0 policies to your API Gateway runtimes using an external identity providers, please refer to the following documentation page, to fill the needed form to start the process.

https://docs.mulesoft.com/anypoint-platform-administration/setting-up-external-identity#providing-mulesoft-the-information-required-to-configure-your-anypoint-platform-organization-for-ping-federate

The current supported provided are PingFederate or OpenAM.

If all you want to use is user management, so you can sign in to the Anypoint platform using your federated credentials (SAML 2.0), you can register your identity manager directly, as explained in the following documentation page:

https://docs.mulesoft.com/anypoint-platform-administration/setting-up-external-identity#instructions-for-saml-configuration

URL: https://docs.mulesoft.com/anypoint-platform-administration/setting-up-external-identity
*** Please check this with Pablo C. and correct grammar, spelling and structure. Thanks! ***

**Comment by fermujica** [comment]
As part of the update for the access-management section, I´m working with the core services team to update the external identity management section. 
We are differencing the steps for configuring **Users** and **Clients** management.

> The current supported provided are PingFederate or OpenAM.

To my knowledge, this is no longer the case. Currently there are a lot of providers that we can work with. Too many to keep track of all of them, so adding proper instructions for each one is a little risky. Customers should check their IdPs instructions as well.

**Comment by fermujica** [comment]
An updated version considering the suggestions made in this issue was pushed in [91dafb0](https://github.com/mulesoft/mulesoft-docs/commit/91dafb00b1464f6349c4987c276495cb8b794a51)
