### ISSUE TITLE
Describe how certificates (ssl) work in CH

### ISSUE THREAD

**Issue by JoshRosso** [mulesoft/mulesoft-docs#273]
Currently building an HTTPS Service (https://docs.mulesoft.com/cloudhub/building-an-https-service) is fairly vague. Customers are unaware of the LB's used by CH so it can be confusing to them that the cert they configure here is not going to be sent to the client. Instead it will be used to communicate between the lb and the worker.

They should be made aware of the automatically used *.cloudhub.io cert that the LB will be sending the client.

**Comment by fermujica** [comment]
Hi Josh. 
Is this still an issue for customers?

A couple of updates were added to the [CH networking guide](/runtime-manager/cloudhub-networking-guide#load-balancing) to explain how the general load balancer works.

**Comment by JoshRosso** [comment]
The enhanced CH networking guide has been a huge help and makes this issue no longer relevant.
