### ISSUE TITLE
Document the attribute apikitRef within api-platform-gw:api

### ISSUE THREAD

**Issue by JoshRosso** [mulesoft/mulesoft-docs#304]
Document the attribute `apikitRef` within `api-platform-gw:api`. We need to expand on the current schema which states:

```
A reference to the APIKit configuration.
```

This element is responsible for uploading the RAML to the platform after the api registers successfully.

Cross-ref for schema update request:
JIRA: AGW-744 [mulesoft internal only]

**Comment by george-hoffer** [comment]
Added via resolving merge requests 306 & 307. Verify at https://docs.mulesoft.com/anypoint-platform-for-apis/api-auto-discovery.
