### ISSUE TITLE
Fix API Auto Discovery section: id attribute and discovery flow graphic

### ISSUE THREAD

**Issue by JoshRosso** [mulesoft/mulesoft-docs#305]
Update API Auto Discovery section: id attribute and discovery flow graphic

**id attribute:**
This current description
> The ID of the global element, which you reference in the api-ref attribute in your endpoint.

This is now simply a bean-id that is not referenced from the old `register-as` component.

**discovery flow graphic:**
The following graphic is no longer correct as of 2.x. Considering `api-ref` and `register-as` are no longer used.
![image](https://cloud.githubusercontent.com/assets/6200057/12993009/8f393d8e-d0cc-11e5-8ec2-ee0ec676e718.png)

**Comment by george-hoffer** [comment]
Added via resolving merge requests 306 & 307. Verify at https://docs.mulesoft.com/anypoint-platform-for-apis/api-auto-discovery.
