### ISSUE TITLE
Outdated name of Update site in file "setting-up-your-dev-environment.adoc"

### ISSUE THREAD

**Issue by MiroslavMeca-Profiq** [mulesoft/mulesoft-docs#308]
Name of the documentation doesn't reflect reality. Since DevKit has new separate URL from addons (http://studio.mulesoft.org/r4/devkit) - changed in [1d55971](https://github.com/mulesoft/mulesoft-docs/commit/1d55971d7f1947441f5bb5247ac790c797c8cb6c) commit - and is added to available sites in Anypoint Studio the documentation should reflect it.

Change this:
> In the Install menu's *Work with* drop-down menu, click the down arrow and click *Anypoint Addons Update Site*. Click the checkbox for *Anypoint DevKit Plugin*, and click *Next*.

To this:
> In the Install menu's *Work with* drop-down menu, click the down arrow and click *Anypoint* **_DevKit_** *Update Site*. Click the checkbox for *Anypoint DevKit Plugin*, and click *Next*.

It can be found in:
- [this /v/3.8](https://github.com/mulesoft/mulesoft-docs/blame/master/anypoint-connector-devkit/v/3.8/setting-up-your-dev-environment.adoc#L77) file
- [this /v/3.7](https://github.com/mulesoft/mulesoft-docs/blame/master/anypoint-connector-devkit/v/3.7/setting-up-your-dev-environment.adoc#L75) file

**Comment by FilipVavera** [comment]
There also should be a new image. Instead of _AddOns+Update+Site.png_ there should be for example this image:
![DevKit+Update+Site.png](https://cloud.githubusercontent.com/assets/10463168/13006108/d89daedc-d186-11e5-927f-a8d3f9bf2429.png)

**Comment by sharkberto** [comment]
Thanks for pointing this out! Changes are building to the site now.
