### ISSUE TITLE
Bad URL in documentation files

### ISSUE THREAD

**Issue by MiroslavMeca-Profiq** [mulesoft/mulesoft-docs#328]
In file **"setting-up-and-managing-users-via-ldap.adoc"** and in section **“Downloading and installing the Apache directory studio LDAP browser”** is bad url link in sentence 
> "...Installation instructions for each supported platform can be found here." (https://github.com/mulesoft/mulesoft-docs/blame/master/mule-management-console/v/3.7/setting-up-and-managing-users-via-ldap.adoc#L252)

Actual: 
> http://directory.apache.org/studio/static/users_guide/apache_directory_studio/download_install.html

Correct: 
> http://directory.apache.org/studio/users-guide/apache_directory_studio/download_install.html
 eventually 
> http://directory.apache.org/studio/users-guide/Apache_Directory_Studio_User_Guide.pdf

**Comment by MiroslavMeca-Profiq** [comment]
In file **"rest-api-reference.adoc"** and in section **"Intended Audience"** is bad url link.

> "... For information on installing, configuring and running Mule ESB, consult the Mule 3 User Guide." [In documentation here...](https://github.com/mulesoft/mulesoft-docs/blame/master/mule-management-console/v/3.7/rest-api-reference.adoc#L9)

Actual:
> https://docs.mulesoft.com/display/MULE3USER/Home

I think that correct is:
> https://docs.mulesoft.com/mule-user-guide/v/3.7/

**Comment by george-hoffer** [comment]
Thank you for letting us know about these issues. Both are now fixed. You can verify these changes at:

https://docs.mulesoft.com/mule-management-console/v/3.7/setting-up-and-managing-users-via-ldap#downloading-and-installing-the-apache-directory-studio-ldap-browser

https://docs.mulesoft.com/mule-management-console/v/3.7/rest-api-reference
