### ISSUE TITLE
Missing stored procedures examples at database-connector-examples

### ISSUE THREAD

**Issue by adrianpineyro** [mulesoft/mulesoft-docs#367]
Please create additional examples based on the test cases available at https://github.com/mulesoft/mule/tree/mule-3.x/modules/db/src/test/resources/integration/storedprocedure

Specially around SP returning resultset/s.

**Comment by sharkberto** [comment]
example added. will release with the database-connector user guide releasing with Mule 3.8

**Comment by adrianpineyro** [comment]
Thanks! I am only seeing one single and simple example on 3.8 docs, and not on 3.7:

https://docs.mulesoft.com/mule-user-guide/v/3.7/database-connector#sts=Database Connector

I couldn't find the database-connector user guide, is it published now? The example pages doesn't have any store procedure or function example.
