### ISSUE TITLE
Document how to setup a proxy for WSC

### ISSUE THREAD

**Issue by JoshRosso** [mulesoft/mulesoft-docs#413]
It can be unclear to Mule developers how to setup a proxy for their outbound WSC calls. While there is a clear reference to an http:request-config, it does not imply that's a means of configuring a proxy.

See http://www.corralict.nl/wsc-connector-proxy/ for a great example.

**Comment by sharkberto** [comment]
https://docs.mulesoft.com/mule-user-guide/v/3.8/web-service-consumer
Added mention of steps to do this per the link you provided. Please see also https://github.com/mulesoft/mulesoft-docs/pull/757
