### ISSUE TITLE
How to configure memory used by Mule ESB Standalone Server

### ISSUE THREAD

**Issue by adrianpineyro** [mulesoft/mulesoft-docs#427]
I couldn't find a documentation page that explains how to set up memory allocation for the mule process.

I was expecting to find some mention here:

https://docs.mulesoft.com/mule-user-guide/v/3.7/installing
https://docs.mulesoft.com/mule-user-guide/v/3.7/starting-and-stopping-mule-esb

Some resources that might help for creating this content:

https://wrapper.tanukisoftware.com/doc/english/prop-java-maxmemory.html
https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/sizing.html
https://docs.oracle.com/cd/E26576_01/doc.312/e24936/tuning-java.htm#abeik

**Comment by sharkberto** [comment]
Per MMC Mule 3.7 distro 
# Maximum Java Heap Size (in MB)
wrapper.java.maxmemory=1024
Will doc. Thanks!
