### ISSUE TITLE
several missing graphics in the README

### ISSUE THREAD

**Issue by PaulAndersonMule** [mulesoft/mulesoft-docs#447]
https://github.com/mulesoft/mulesoft-docs/blob/c89a5a0b8df8a594f61c46d0ac4af27a7d4be6a9/anypoint-platform-on-premises/v/1.1.0/installing-anypoint-on-premises.adoc#system-requirements

see broken graphics URLs. Would do a PR if I knew where those graphics were stored

**Comment by nearnshaw** [comment]
The link you're pointing at is the Github fast build, where images never show, that's normal and expected with our build process.
The actual site build that produces the true site is working fine and showing images as expected:  https://docs.mulesoft.com/anypoint-platform-on-premises/v/1.1.0/installing-anypoint-on-premises

I will close this issue, as nothing is truly wrong here
