### ISSUE TITLE
classpath must be specified when doing spring:import on external xml

### ISSUE THREAD

**Issue by JoshRosso** [mulesoft/mulesoft-docs#531]
Classpath must be specified when doing spring import. E.g. - example at https://docs.mulesoft.com/mule-user-guide/v/3.6/sharing-custom-configuration-fragments will not resolve.

I'll send a PR in tonight.

**Comment by george-hoffer** [comment]
Changed code example to:
<spring:beans>
  <spring:import resource="classpath:myCommonFlow.xml"/>
</spring:beans>

And added note about the need to supply a classpath. Fixed in 3.6, 3.7, 3.8 versions of this doc.

**Comment by george-hoffer** [comment]
Hi Josh, If this issue is resolved as you require, would you close it?  Thank you for helping improve MuleSoft docs.
