### ISSUE TITLE
Wrong URLs in the file "api-quick-start.adoc"

### ISSUE THREAD

**Issue by MiroslavMeca-Profiq** [mulesoft/mulesoft-docs#602]
File **"api-quick-start.adoc"** has some wrong URLs.

1. ["How to create an automatic test for your application"](https://github.com/mulesoft/mulesoft-docs/blame/master/anypoint-platform-for-apis/v/latest/api-quick-start.adoc#L11)
Actaul URL is  "https://docs.mulesoft.com/anypoint-platform-for-apis/create-an-automatic-munit-test", but maybe correct is "https://docs.mulesoft.com/quickstarts/implement-and-test#create-an-munit-test" or "https://docs.mulesoft.com/munit/v/1.2.0/using-munit-in-anypoint-studio".

2. ["auto-discovery"](https://github.com/mulesoft/mulesoft-docs/blame/master/anypoint-platform-for-apis/v/latest/api-quick-start.adoc#L12)
Actual URL is "https://docs.mulesoft.com/anypoint-platform-for-apis/create-an-api-from-an-existing-raml#deploy-the-api-to-anypoint-platform-for-auto-discovery" but maybe correct is "https://docs.mulesoft.com/anypoint-platform-for-apis/apikit-tutorial#creating-a-new-project" or "https://docs.mulesoft.com/quickstarts/implement-and-test#create-a-project-based-on-a-raml" or "https://docs.mulesoft.com/anypoint-platform-for-apis/api-auto-discovery".

3. ["API Sync"](https://github.com/mulesoft/mulesoft-docs/blame/master/anypoint-platform-for-apis/v/latest/api-quick-start.adoc#L13)
Actual URL is "https://docs.mulesoft.com/anypoint-platform-for-apis/sync-your-api-with-anypoint-platform" but correct is "https://docs.mulesoft.com/anypoint-platform-for-apis/api-sync-reference"

4. ["creating an API in Anypoint Platform"](https://github.com/mulesoft/mulesoft-docs/blame/master/anypoint-platform-for-apis/v/latest/api-quick-start.adoc#L15)
Actual URL is "https://docs.mulesoft.com/anypoint-platform-for-apis/create-an-api" but correct is "https://docs.mulesoft.com/anypoint-platform-for-apis/creating-your-api-in-the-anypoint-platform#creating-an-api"

**Comment by fermujica** [comment]
Thanks for reporting this and apologies for the late response.
All these articles have been moved to the /api-manager/ section and those links have been updated.

I searched the repository for references to those links and couldn´t find any. 

Please let me know if you still see broken or irrelevant links across the docs.
