### ISSUE TITLE
Limitation when using Runtime Manager

### ISSUE THREAD

**Issue by adrianpineyro** [mulesoft/mulesoft-docs#625]
At the deploying-to-your-own-servers.adoc page, it should be clarified that dual management must be avoid. When using runtime manager, other deployment and management methods and/or tools must be avoided (e.g.: manual deployment, MMC).

**Comment by nearnshaw** [comment]
Added note about this to the start of 
https://docs.mulesoft.com/runtime-manager/deploying-to-your-own-servers#
