### ISSUE TITLE
Retained link to a deleted file 'creating-a-connector-for-a-restful-api-using-restcall-annotations.adoc'

### ISSUE THREAD

**Issue by MiroslavMeca-Profiq** [mulesoft/mulesoft-docs#643]
The file 'creating-a-connector-for-a-restful-api-using-restcall-annotations.adoc' was removed. But the [page](https://docs.mulesoft.com/anypoint-connector-devkit/v/3.8/) ([GitHub Doc](https://github.com/mulesoft/mulesoft-docs/blob/master/anypoint-connector-devkit/v/3.8/index.adoc)) has URL links to the removed file. These links should be removed or replaced.

This URLs are located in section "Anypoint Connector DevKit Features>API Types" and "See Also".

1. [REST Apis](https://github.com/mulesoft/mulesoft-docs/blame/master/anypoint-connector-devkit/v/3.8/index.adoc#L220)
2. [Creating a Connector for a RESTful API using @RESTCall Annotations](https://github.com/mulesoft/mulesoft-docs/blame/master/anypoint-connector-devkit/v/3.8/index.adoc#L253)

_Here are references to older versions file which is not in version 3.8: [v3.5](https://github.com/mulesoft/mulesoft-docs/blob/master/anypoint-connector-devkit/v/3.5/creating-a-connector-for-a-restful-api-using-restcall-annotations.adoc), [v3.6](https://github.com/mulesoft/mulesoft-docs/blob/master/anypoint-connector-devkit/v/3.6/creating-a-connector-for-a-restful-api-using-restcall-annotations.adoc), and [v3.7](https://github.com/mulesoft/mulesoft-docs/blob/master/anypoint-connector-devkit/v/3.7/creating-a-connector-for-a-restful-api-using-restcall-annotations.adoc)._

Also when click the link (for example [REST Apis](https://docs.mulesoft.com/anypoint-connector-devkit/v/3.8/creating-a-connector-for-a-restful-api-using-restcall-annotations))so it is displayed information message **"The page isn't redirecting properly"**. 
I think it occurs because HTTP reply status code is 301, then it redirect between from HTTPS to HTTP protocols and conversely. Over and over again.

It could be better if HTTP reply status was 404 Page not found.

**I tried/tested it on:** Ubuntu 16.04 - Mozilla, Chrome; Windows 10 - Microsoft Edge, Internet Explorer

**Comment by george-hoffer** [comment]
Fixed as requested. Verify at https://docs.mulesoft.com/anypoint-connector-devkit/v/3.8/
If you're satisfied with this fix, please close this issue.
Thank you for helping improve MuleSoft documentation.
