### ISSUE TITLE
creating-a-connector-for-a-restful-api-using-jersey

### ISSUE THREAD

**Issue by adrianpineyro** [mulesoft/mulesoft-docs#668]
This document should be removed. The tutorial does not longer works with the latest version of DevKit. Even the POM shows an older version, when visiting 3.8:

<version>3.6.1</version>

Our suggestion is to replace all the DevKit Docs with the CookBook or validate its contents against it:

http://mulesoft.github.io/mule-cookbook-tutorial/

**Comment by sharkberto** [comment]
The recommended approach still seems to be using a Jersey client to support REST API functionality. Can we not update this doc?
