### ISSUE TITLE
Failed to invoke getUserTimelineByScreenName. Message payload is of type: NullPayload

### ISSUE THREAD

**Issue by M-Thirumal** [mulesoft/mulesoft-docs#70]
I followed the same tutorial from https://docs.mulesoft.com/mule-fundamentals/v/3.7/anypoint-connector-tutorial.

Even copy pasted but I am getting the following errors 
Failed to invoke getUserTimelineByScreenName. Message payload is of type: NullPayload

Same problem with box connector also 

Thanks in advance

**Comment by george-hoffer** [comment]
Hi - Thank you for this issue. I rewrote the Anypoint Connector Tutorial on 29/Dec/2015 to make it clearer and tested the procedures in the process. Please try going through this document again to see if you get the same error.

**Comment by george-hoffer** [comment]
If you have further concerns, please open a new issue. Closing this one. Thank you for helping improve MuleSoft documentation.
