### ISSUE TITLE
Unable to run mule.sh on Ubuntu 16.04, returns "683: mule: Permission denied"

### ISSUE THREAD

**Issue by TESAARON** [mulesoft/mulesoft-docs#838]
Hello,

I am having trouble running the mule runtime on a Linux Ubuntu 16.04 system. When I navigate to the bin directory in the standalone folder and run:

sudo sh mule

I get the following error:
683: mule: /home/TESAaron/MuleSoft/mule-standalone-3.8.0/bin/mule: Permission denied

Any ideas how I can rectify this?

Many thanks,
Aaron

**Comment by TESAARON** [comment]
P.S. This is mule standalone version 3.8.0

**Comment by yjkimjunior** [comment]
You may want to try changing the permissions. 
`chmod +x mule`

**Comment by TESAARON** [comment]
Yes I have made mule executable using the command you mentioned but the problem still remains.
