### ISSUE TITLE
managing-schedules.adoc

### ISSUE THREAD

**Issue by adrianpineyro** [mulesoft/mulesoft-docs#868]
There are no clarifications around what happens with the Quartz transport (instead of using the Poll scope) and how the scheduler behaves when the application run in multiple workers.

Thanks!

**Comment by sharkberto** [comment]
Thanks Adrian, we are looking into this.

**Comment by sharkberto** [comment]
https://docs.mulesoft.com/runtime-manager/managing-schedules - are there differences in managing apps with poll scope versus quartz? There is a "Switch to advanced mode" button and then a mention of cron jobs @nearnshaw also a link to a Quartz CronTrigger tutorial...do we need to clarify anything regarding use of Quartz?

**Comment by mikecon94** [comment]
It's worth noting that when running in an environment with multiple workers/nodes a quartz scheduler, by default, will run on each node whereas the Poll Scope is "smart" enough to only run on a single node.
A quartz scheduler can be configured to work this way but requires configuration of a [JDBC JobStore](http://www.quartz-scheduler.org/documentation/quartz-2.x/configuration/ConfigJDBCJobStoreClustering).

**Comment by sleslie23** [comment]
@adrianpineyro Hey Adrian! Sorry this has not been address sooner. I'll file a JIRA issue and fix this when I am back from vacation (July 5). Thanks!

**Comment by george-hoffer** [comment]
Added this note to the 3.4-3.9 Quartz Transport Reference:
*Note:* When running in an environment with multiple workers or nodes, a Quartz scheduler, by default, runs on each node, whereas a Poll Scope only runs on a single node. A Quartz scheduler can be configured to work this way but requires configuration of a JDBC JobStore.

**Comment by george-hoffer** [comment]
Resolved all issues and Adrian approved changes. He said this is ok to close.
