### ISSUE TITLE
Request to update documentation part upgrading-mule-runtime-versions

### ISSUE THREAD

**Issue by flavioOrfano** [mulesoft/mulesoft-docs#913]
On the Upgrading-mule-runtime-versions documentation area we should add the information that  it requires to have the agent installed otherwise a NPE is throw. Note for the NPE there is a SE JIRA created. 

https://github.com/mulesoft/mulesoft-docs/blob/master/release-notes/v/latest/updating-mule-versions.adoc#upgrading-mule-runtime-versions

**Comment by nearnshaw** [comment]
Thanks Flavio, I just added a note to this doc to clarify that you need to have the Agent in your old runtime to follow the steps explained here
