### ISSUE TITLE
Missing first image of reliability pattern

### ISSUE THREAD

**Issue by ikazeemi** [mulesoft/mulesoft-docs#963]
Missing first image of reliability pattern

https://docs.mulesoft.com/mule-user-guide/v/3.7/reliability-patterns

**Comment by fermujica** [comment]
Hi Imran,

Thanks for taking the time to report these  errors. 
I'm taking care of these broken images. 

I also saw #964 regarding an example in this very same page. 
If it's just a broken XML, I'll fix that as well.
