### ISSUE TITLE
FTP to VM code example throwing error

### ISSUE THREAD

**Issue by ikazeemi** [mulesoft/mulesoft-docs#964]
Following code is throwing error:

"Error on line 25 of document  : The element type "ftp:inbound-endpoint" must be terminated by the matching end-tag "</ftp:inbound-endpoint>". Nested exception: The element type "ftp:inbound-endpoint" must be terminated by the matching end-tag "</ftp:inbound-endpoint>".
Error on line 25 of document  : The element type "ftp:inbound-endpoint" must be terminated by the matching end-tag "</ftp:inbound-endpoint>". Nested exception: The element type "ftp:inbound-endpoint" must be terminated by the matching end-tag "</ftp:inbound-endpoint>"."

<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:mule="http://www.mulesoft.org/schema/mule/core"
      xmlns:ftp="http://www.mulesoft.org/schema/mule/ftp"
      xmlns:vm="http://www.mulesoft.org/schema/mule/vm"
      xmlns:test="http://www.mulesoft.org/schema/mule/test"
    xsi:schemaLocation="
        http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/3.2/mule.xsd
        http://www.mulesoft.org/schema/mule/test http://www.mulesoft.org/schema/mule/test/3.2/mule-test.xsd
        http://www.mulesoft.org/schema/mule/vm http://www.mulesoft.org/schema/mule/jms/3.2/mule-vm.xsd
        http://www.mulesoft.org/schema/mule/ftp http://www.mulesoft.org/schema/mule/ftp/3.2/mule-ftp.xsd">
 
    <flow name="ftp-reliability" processingStrategy="synchronous">
        <ftp:inbound-endpoint user="dirk" password="dirk" host="localhost" port="2121" path="/">
            <idempotent-redelivery-policy maxRedeliveryCount="2">
                <dead-letter-queue>
                    <vm:endpoint path="error-queue" />
                </dead-letter-queue>
            </idempotent-redelivery-policy>
        <ftp:inbound-endpoint/>
        <custom-transformer class="mycompany.mule.transformers.FTPInput"/>
        <vm:outbound-endpoint path="from-ftp" exchange-pattern="one-way"/>
    </flow>
</mule>

**Comment by nearnshaw** [comment]
Thanks for reporting this Irman!
I just fixed the code example in this doc.  There was a very dumb error with the XML, where the closing tag had the slash at the end instead of the start of the tag, 

ie:
<ftp:inbound-endpoint/>
instead of:
</ftp:inbound-endpoint>
